version: '3.9'

services:
  db:
    image: postgres:16
    container_name: care_roster_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: care_roster
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: care_roster_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: care_roster_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: care_roster
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db
